export enum Role {
  SUPER_ADMIN = 'Super Admin',
  CORE_TEAM_ADMIN = 'Core Team Admin',
  TEAM_HEAD = 'Team Head',
  CONTENT_EDITOR = 'Content Editor',
  VIEWER = 'Viewer',
}

export enum Permission {
  CONTENT_READ = 'content.read',
  CONTENT_EDIT = 'content.edit',
  CONTENT_PUBLISH = 'content.publish',
  PEOPLE_READ = 'people.read',
  PEOPLE_EDIT = 'people.edit',
  TEAMS_READ = 'teams.read',
  TEAMS_EDIT = 'teams.edit',
  INITIATIVES_READ = 'initiatives.read',
  INITIATIVES_EDIT = 'initiatives.edit',
  STORIES_READ = 'stories.read',
  STORIES_EDIT = 'stories.edit',
  STAKEHOLDERS_READ = 'stakeholders.read',
  STAKEHOLDERS_EDIT = 'stakeholders.edit',
  HERO_MANAGE = 'hero.manage',
  MEDIA_UPLOAD = 'media.upload',
  MEDIA_MANAGE = 'media.manage',
  SUBMISSIONS_READ = 'submissions.read',
  SUBMISSIONS_MANAGE = 'submissions.manage',
  SUBMISSIONS_EXPORT = 'submissions.export',
  FORMS_READ = 'forms.read',
  FORMS_CREATE = 'forms.create',
  FORMS_EDIT = 'forms.edit',
  FORMS_PUBLISH = 'forms.publish',
  FORMS_RESPONSES_READ = 'forms.responses.read',
  FORMS_RESPONSES_EXPORT = 'forms.responses.export',
  COPILOT_USE = 'copilot.use',
  COPILOT_CONFIRM = 'copilot.confirm',
  USERS_MANAGE = 'users.manage',
  AUDIT_READ = 'audit.read',
}

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.SUPER_ADMIN]: Object.values(Permission),
  [Role.CORE_TEAM_ADMIN]: [
    Permission.CONTENT_READ,
    Permission.CONTENT_EDIT,
    Permission.CONTENT_PUBLISH,
    Permission.PEOPLE_READ,
    Permission.PEOPLE_EDIT,
    Permission.TEAMS_READ,
    Permission.TEAMS_EDIT,
    Permission.INITIATIVES_READ,
    Permission.INITIATIVES_EDIT,
    Permission.STORIES_READ,
    Permission.STORIES_EDIT,
    Permission.STAKEHOLDERS_READ,
    Permission.STAKEHOLDERS_EDIT,
    Permission.HERO_MANAGE,
    Permission.MEDIA_UPLOAD,
    Permission.MEDIA_MANAGE,
    Permission.SUBMISSIONS_READ,
    Permission.SUBMISSIONS_MANAGE,
    Permission.SUBMISSIONS_EXPORT,
    Permission.FORMS_READ,
    Permission.FORMS_CREATE,
    Permission.FORMS_EDIT,
    Permission.FORMS_PUBLISH,
    Permission.FORMS_RESPONSES_READ,
    Permission.FORMS_RESPONSES_EXPORT,
    Permission.COPILOT_USE,
    Permission.COPILOT_CONFIRM,
    Permission.USERS_MANAGE,
    Permission.AUDIT_READ,
  ],
  [Role.TEAM_HEAD]: [
    Permission.CONTENT_READ,
    Permission.TEAMS_READ,
    Permission.TEAMS_EDIT,
    Permission.PEOPLE_READ,
    Permission.INITIATIVES_READ,
    Permission.STORIES_READ,
    Permission.MEDIA_UPLOAD,
    Permission.SUBMISSIONS_READ,
    Permission.SUBMISSIONS_MANAGE,
    Permission.FORMS_READ,
    Permission.FORMS_CREATE,
    Permission.FORMS_EDIT,
    Permission.FORMS_RESPONSES_READ,
    Permission.COPILOT_USE,
  ],
  [Role.CONTENT_EDITOR]: [
    Permission.CONTENT_READ,
    Permission.CONTENT_EDIT,
    Permission.PEOPLE_READ,
    Permission.PEOPLE_EDIT,
    Permission.TEAMS_READ,
    Permission.INITIATIVES_READ,
    Permission.INITIATIVES_EDIT,
    Permission.STORIES_READ,
    Permission.STORIES_EDIT,
    Permission.STAKEHOLDERS_READ,
    Permission.STAKEHOLDERS_EDIT,
    Permission.MEDIA_UPLOAD,
    Permission.MEDIA_MANAGE,
    Permission.FORMS_READ,
    Permission.FORMS_CREATE,
    Permission.FORMS_EDIT,
    Permission.COPILOT_USE,
  ],
  [Role.VIEWER]: [
    Permission.CONTENT_READ,
    Permission.PEOPLE_READ,
    Permission.TEAMS_READ,
    Permission.INITIATIVES_READ,
    Permission.STORIES_READ,
    Permission.STAKEHOLDERS_READ,
    Permission.FORMS_READ,
    Permission.AUDIT_READ,
  ],
};
