import {
  HeroSpotlight,
  Person,
  Team,
  Initiative,
  Story,
  Partner,
  Speaker,
  Startup,
  Alumni,
  MediaAsset,
  Submission,
  GoogleForm,
  GoogleFormResponse,
  CopilotMessage,
  AuditLog,
  SiteSettings,
  CmsUser,
} from './types';

export const mockUsers: CmsUser[] = [
  {
    id: 'usr-001',
    name: 'Aarav Sharma',
    email: 'president@gec.in',
    role: 'super_admin',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2026-09-20T10:15:00Z',
  },
  {
    id: 'usr-002',
    name: 'Pooja Verma',
    email: 'admin.core@gec.in',
    role: 'core_admin',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2026-09-20T11:42:00Z',
  },
  {
    id: 'usr-003',
    name: 'Rohan Gupta',
    email: 'tech.head@gec.in',
    role: 'team_head',
    teamScope: 'team_06',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2026-09-19T18:20:00Z',
  },
  {
    id: 'usr-004',
    name: 'Sneha Patel',
    email: 'editorial@gec.in',
    role: 'content_editor',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2026-09-20T09:30:00Z',
  },
  {
    id: 'usr-005',
    name: 'Prof. Rajesh K.',
    email: 'mentor.audit@gec.in',
    role: 'viewer',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2026-09-18T14:10:00Z',
  },
];

export const mockHeroSpotlight: HeroSpotlight = {
  id: 'hero-camp-001',
  campaignName: 'Startup Development Program — Cohort 04',
  status: 'Applications Open',
  priority: 'P1',
  headline: 'STARTUP DEVELOPMENT PROGRAM 2026',
  supportingText: 'Have a validated problem or prototype? Join northern India’s premier university incubation funnel with seed grants up to ₹5 Lakhs.',
  eyebrowBadge: 'APPLICATIONS OPEN · COHORT 04',
  desktopVideo: 'https://media-staging.gec.in/videos/sdp-cohort-4-loop-16x9.mp4',
  mobileVideo: 'https://media-staging.gec.in/videos/sdp-cohort-4-loop-9x16.mp4',
  desktopPoster: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1600&auto=format&fit=crop&q=80',
  mobilePoster: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=900&auto=format&fit=crop&q=80',
  primaryCtaText: 'Apply for Cohort 04',
  primaryCtaUrl: '/initiatives/sdp-cohort-04',
  secondaryCtaText: 'Explore Incubation Perks',
  secondaryCtaUrl: '/initiatives',
  startDatetime: '2026-09-15T09:00:00Z',
  endDatetime: '2026-10-10T23:59:59Z',
  publishStatus: 'Live',
  fallbackBehavior: 'evergreen_brand',
  secondaryItems: [
    {
      id: 'spot-02',
      indexNum: '01',
      title: 'Galgotias Ideathon 2026',
      category: 'Flagship Hackathon',
      url: '/initiatives/ideathon-2026',
    },
    {
      id: 'spot-03',
      indexNum: '02',
      title: 'E-Cell Autumn Recruitment',
      category: 'Join 7 Teams',
      url: '/teams',
    },
  ],
};

export const mockPeople: Person[] = [
  {
    id: 'per-001',
    fullName: 'Dr. Vikramaditya Sen',
    designation: 'Faculty Chief Advisor & Director, GICRISE',
    tier: 'mentors_tier_2',
    department: 'School of Computing Science & Incubation',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    linkedinUrl: 'https://linkedin.com',
    bio: 'Pioneered collegiate incubation models in NCR with over 120 mentored student ventures.',
    active: true,
  },
  {
    id: 'per-002',
    fullName: 'Aarav Sharma',
    designation: 'President, GEC',
    tier: 'leadership_tier_1',
    department: 'B.Tech Computer Science',
    graduationYear: '2027',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    linkedinUrl: 'https://linkedin.com',
    twitterUrl: 'https://x.com',
    bio: 'Leading strategic partnerships, institutional grants, and high-impact founder cohorts.',
    active: true,
  },
  {
    id: 'per-003',
    fullName: 'Ananya Deshmukh',
    designation: 'Vice President, GEC',
    tier: 'leadership_tier_1',
    department: 'B.Tech Information Technology',
    graduationYear: '2027',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    linkedinUrl: 'https://linkedin.com',
    bio: 'Oversees operational execution across 7 teams and cohort milestone tracking.',
    active: true,
  },
  {
    id: 'per-004',
    fullName: 'Kabir Singhania',
    designation: 'Head, Startup Development (Team 01)',
    tier: 'team_heads_tier_3',
    department: 'B.Tech Mechanical Engineering',
    graduationYear: '2027',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    linkedinUrl: 'https://linkedin.com',
    bio: 'Runs investor pitch clinics, founder Office Hours, and pre-incubation screening.',
    active: true,
    teamId: 'team_01',
  },
  {
    id: 'per-005',
    fullName: 'Rhea Nambiar',
    designation: 'Head, PR & External Networking (Team 02)',
    tier: 'team_heads_tier_3',
    department: 'BBA Entrepreneurship',
    graduationYear: '2027',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    linkedinUrl: 'https://linkedin.com',
    bio: 'Curator of ecosystem alliances, investor networks, and guest keynote speakers.',
    active: true,
    teamId: 'team_02',
  },
  {
    id: 'per-006',
    fullName: 'Rohan Gupta',
    designation: 'Head, Technical Team (Team 06)',
    tier: 'team_heads_tier_3',
    department: 'B.Tech CSE Data Science',
    graduationYear: '2027',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
    linkedinUrl: 'https://linkedin.com',
    githubUrl: 'https://github.com',
    bio: 'Architect of GEC digital infrastructure, platform microservices, and student hack portals.',
    active: true,
    teamId: 'team_06',
  },
  {
    id: 'per-007',
    fullName: 'Devansh Kulkarni',
    designation: 'Lead Platform Coordinator (Team 06)',
    tier: 'coordinators_tier_3',
    department: 'B.Tech AI & ML',
    graduationYear: '2028',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    linkedinUrl: 'https://linkedin.com',
    active: true,
    teamId: 'team_06',
  },
  {
    id: 'per-008',
    fullName: 'Tanya Saxena',
    designation: 'Founding Member & E-Summit Convener',
    tier: 'alumni_tier_4',
    department: 'Alumni 2025 · Founder @ FleetOps',
    graduationYear: '2025',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    linkedinUrl: 'https://linkedin.com',
    bio: 'Raised $650k Pre-Seed; advisory board member for student venture fund.',
    active: true,
  },
];

export const mockTeams: Team[] = [
  {
    id: 'team_01',
    number: '01',
    name: 'Startup Development',
    slug: 'startup-development',
    accentColor: '#FBCA05', // Gold
    themeBadge: 'bg-[#FBCA05]/20 text-[#A16207] border-[#FBCA05]/40',
    tagline: 'Turning raw student sparks into scalable venture equity.',
    mission: 'Identify, pre-incubate, and accelerate high-potential student founders with milestone-driven grants, IP protection, and investor pitch sessions.',
    overview: 'Team 01 is the direct engine of campus entrepreneurship. We vet cohort applications, conduct teardowns of business models, and organize pitch days before angel networks.',
    headId: 'per-004',
    headName: 'Kabir Singhania',
    headDesignation: 'Head, Startup Development',
    headPhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    coordinators: [
      { id: 'c-01', name: 'Nikhil Rathi', role: 'Incubation Associate', photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80' },
      { id: 'c-02', name: 'Tanvi Kapoor', role: 'Cohort Ops Lead', photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80' },
    ],
    membersCount: 18,
    responsibilities: [
      { id: 'p-1', title: 'Cohort Pre-Incubation', scope: 'Screening 150+ startup pitches each semester and organizing 8-week bootcamps.' },
      { id: 'p-2', title: 'Investor Pitch Clinics', scope: 'Preparing founders with financials, unit economics, and cap table fundamentals.' },
      { id: 'p-3', title: 'Office Hours & Mentorship', scope: 'Connecting active student ventures with serial entrepreneurs and domain experts.' },
      { id: 'p-4', title: 'Patent & IP Advisory', scope: 'Assisting student researchers with filing patents through university IP cell.' },
      { id: 'p-5', title: 'Seed Grant Governance', scope: 'Reviewing milestone achievement and disbursing proof-of-concept capital.' },
      { id: 'p-6', title: 'Alumni Founder Network', scope: 'Maintaining direct relations with scaled alumni startups for student mentorship.' },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/company/gec-startup-dev',
      email: 'startupdev@gec.in',
    },
    gallery: [
      'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80',
    ],
    recruitmentStatus: 'open',
    recruitmentDeadline: '2026-10-05T23:59:59Z',
    applicationsCount: 42,
  },
  {
    id: 'team_02',
    number: '02',
    name: 'Public Relations & Networking',
    slug: 'pr-networking',
    accentColor: '#A3040F', // Crimson
    themeBadge: 'bg-[#A3040F]/15 text-[#A3040F] border-[#A3040F]/30',
    tagline: 'Bridging campus builders to global venture capital ecosystems.',
    mission: 'Establish high-impact institutional alliances, secure prominent keynote speakers, and maintain active relations with incubators across the country.',
    overview: 'Team 02 secures corporate sponsors, manages VCs and angels who attend our summits, and drives GEC prestige across institutional circles.',
    headId: 'per-005',
    headName: 'Rhea Nambiar',
    headDesignation: 'Head, PR & Networking',
    headPhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
    coordinators: [
      { id: 'c-03', name: 'Manish Chawla', role: 'Sponsorship Lead', photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80' },
      { id: 'c-04', name: 'Ishita Bansal', role: 'VIP Hospitality Head', photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80' },
    ],
    membersCount: 14,
    responsibilities: [
      { id: 'p-7', title: 'Venture Capital Partnerships', scope: 'Aligning top micro-VCs and angel syndicates to judge and fund student demo days.' },
      { id: 'p-8', title: 'Corporate Sponsorships', scope: 'Securing multi-lakh sponsorship deals for flagship annual gatherings.' },
      { id: 'p-9', title: 'Keynote Speaker Curation', scope: 'Hosting Unicorn founders, institutional leaders, and prominent policy makers.' },
      { id: 'p-10', title: 'Cross-University Alliances', scope: 'Partnering with IIT/IIM E-Cells for multi-campus hackathons.' },
      { id: 'p-11', title: 'VIP Dignitary Protocol', scope: 'Managing on-ground hospitality and protocol for distinguished guests.' },
      { id: 'p-12', title: 'Press & Media Relations', scope: 'Publishing official press statements and securing regional/national media coverage.' },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/company/gec-pr',
      email: 'pr@gec.in',
    },
    gallery: [
      'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
    ],
    recruitmentStatus: 'open',
    recruitmentDeadline: '2026-10-05T23:59:59Z',
    applicationsCount: 29,
  },
  {
    id: 'team_03',
    number: '03',
    name: 'Marketing & Campus Ambassador',
    slug: 'marketing-ca',
    accentColor: '#F97316', // Orange
    themeBadge: 'bg-[#F97316]/15 text-[#EA580C] border-[#F97316]/30',
    tagline: 'Igniting student buzz across 30,000+ university minds.',
    mission: 'Execute high-energy guerrilla activations, on-ground blitz campaigns, and build a cohesive network of student ambassadors across every department.',
    overview: 'Team 03 drives attendance, participation, and footfall across every GEC initiative using creative physical and digital growth hacks.',
    headId: 'per-009',
    headName: 'Kunal Mehra',
    headDesignation: 'Head, Marketing',
    headPhoto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    coordinators: [
      { id: 'c-05', name: 'Shruti Sen', role: 'Campus Ambassador Lead', photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80' },
    ],
    membersCount: 22,
    responsibilities: [
      { id: 'p-13', title: 'Guerrilla Marketing', scope: 'Unannounced installations, popup flash challenges, and viral physical stunts.' },
      { id: 'p-14', title: 'CA Network across NCR', scope: 'Managing 120+ ambassadors in colleges across Greater Noida and Delhi NCR.' },
      { id: 'p-15', title: 'Department Outreach', scope: 'Classroom presentations across Engineering, Law, Management, and Pharmacy.' },
      { id: 'p-16', title: 'Merchandise & Swag', scope: 'Designing student founder jackets, stickers, notebook stationery, and badges.' },
      { id: 'p-17', title: 'Ticket & RSVP Conversion', scope: 'Driving registration funnels and ensuring 95%+ event show-up rate.' },
      { id: 'p-18', title: 'Ecosystem Newsletters', scope: 'Weekly student digest highlighting top opportunities and founder jobs.' },
    ],
    socialLinks: {
      instagram: 'https://instagram.com/gec_galgotias',
      email: 'marketing@gec.in',
    },
    gallery: [],
    recruitmentStatus: 'open',
    recruitmentDeadline: '2026-10-05T23:59:59Z',
    applicationsCount: 35,
  },
  {
    id: 'team_04',
    number: '04',
    name: 'Event Management',
    slug: 'event-management',
    accentColor: '#7F1D1D', // Burgundy
    themeBadge: 'bg-[#7F1D1D]/15 text-[#7F1D1D] border-[#7F1D1D]/30',
    tagline: 'Flawless ground-level logistics for flagship university spectacles.',
    mission: 'Design, plan, and execute world-class stages, audio-visuals, security, registration desks, and schedule discipline for over 10,000+ attendees.',
    overview: 'From 48-hour continuous hackathons to auditorium keynotes with 2,500 people, Team 04 executes precision stagecraft without hitches.',
    headId: 'per-010',
    headName: 'Siddharth Bose',
    headDesignation: 'Head, Events & Stage Logistics',
    headPhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    coordinators: [],
    membersCount: 26,
    responsibilities: [
      { id: 'p-19', title: 'Venue Booking & Floorplans', scope: 'Auditorium, open amphitheater, and seminar hall reservations and seating layouts.' },
      { id: 'p-20', title: 'AV & Production', scope: 'LED walls, sound engineering, multi-cam live broadcast, and ambient lighting.' },
      { id: 'p-21', title: 'Crowd Flow & Security', scope: 'Registration queues, badge printing, and crowd safety control.' },
      { id: 'p-22', title: 'Catering & Logistics', scope: 'Food courts, refreshments for 1,000+ overnight hackathon participants.' },
      { id: 'p-23', title: 'Stage Timing & Run-of-Show', scope: 'Minute-by-minute schedule execution and speaker stage timing cueing.' },
      { id: 'p-24', title: 'Vendor & Asset Management', scope: 'Stage fabrication, podium acoustics, and equipment returns.' },
    ],
    socialLinks: { email: 'events@gec.in' },
    gallery: [],
    recruitmentStatus: 'closed',
    applicationsCount: 19,
  },
  {
    id: 'team_05',
    number: '05',
    name: 'Digital Media & Promotions',
    slug: 'digital-media',
    accentColor: '#334155', // Charcoal/Slate
    themeBadge: 'bg-[#334155]/15 text-[#334155] border-[#334155]/30',
    tagline: 'Visual storytelling through editorial lenses and cinematic reels.',
    mission: 'Capture the soul of student grit through high-framerate cinematography, typography-driven poster aesthetics, and viral Instagram narratives.',
    overview: 'Team 05 handles photography, aftermovies, motion typography, and social media storytelling that distinguishes GEC from conventional college clubs.',
    headId: 'per-011',
    headName: 'Aditi Nair',
    headDesignation: 'Head, Media & Creative Content',
    headPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    coordinators: [],
    membersCount: 16,
    responsibilities: [
      { id: 'p-25', title: 'Cinematography & Aftermovies', scope: 'Producing 4K documentary-style recaps of flagship campus milestones.' },
      { id: 'p-26', title: 'Editorial Graphic Design', scope: 'Creating print and digital campaign posters following GEC brand guidelines.' },
      { id: 'p-27', title: 'Reels & Short-Form Video', scope: 'Producing fast-paced Instagram and LinkedIn founder teasers.' },
      { id: 'p-28', title: 'Live Event Photography', scope: 'Capturing high-resolution candid shots of speakers and participants.' },
      { id: 'p-29', title: 'Social Media Management', scope: 'Scheduling copy, stories, and engagement across all active social handles.' },
      { id: 'p-30', title: 'Brand Asset Vault', scope: 'Maintaining high-res SVG vectors, banners, and typography lockups.' },
    ],
    socialLinks: {
      instagram: 'https://instagram.com/gec_media',
      email: 'media@gec.in',
    },
    gallery: [],
    recruitmentStatus: 'open',
    recruitmentDeadline: '2026-10-05T23:59:59Z',
    applicationsCount: 31,
  },
  {
    id: 'team_06',
    number: '06',
    name: 'Technical Team',
    slug: 'technical-team',
    accentColor: '#1F7EC0', // GEC Blue
    themeBadge: 'bg-[#1F7EC0]/15 text-[#1F7EC0] border-[#1F7EC0]/30',
    tagline: 'Engineering high-concurrency systems, digital platforms, and CMS apps.',
    mission: 'Build, maintain, and secure the GEC website, internal CMS, automated submission pipelines, and custom event evaluation portals.',
    overview: 'Team 06 produces production-grade software using modern web frameworks, strict type safety, edge caching, and scalable cloud databases.',
    headId: 'per-006',
    headName: 'Rohan Gupta',
    headDesignation: 'Head, Technical Team',
    headPhoto: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    coordinators: [
      { id: 'c-06', name: 'Devansh Kulkarni', role: 'Fullstack Platform Lead', photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80' },
    ],
    membersCount: 15,
    responsibilities: [
      { id: 'p-31', title: 'Public Web Platform', scope: 'Next.js 16 + React 19 frontend with 99.9% uptime and sub-second page loads.' },
      { id: 'p-32', title: 'Internal CMS Application', scope: 'Industrial command center for student leads with RBAC and media upload.' },
      { id: 'p-33', title: 'AI Copilot & Google Forms', scope: 'Gemini integration for form planning and automated response synchronization.' },
      { id: 'p-34', title: 'Hackathon Judging Engine', scope: 'Custom live scoring dashboards and team match-making tools.' },
      { id: 'p-35', title: 'Security & Cloud Infra', scope: 'Neon Postgres, Cloudflare R2 CDN, Render NestJS services, and SSL policies.' },
      { id: 'p-36', title: 'Open Source Tech Labs', scope: 'Guiding student engineers through contributing to campus software tools.' },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/company/gec-tech',
      twitter: 'https://x.com/gec_tech',
      email: 'tech@gec.in',
    },
    gallery: [],
    recruitmentStatus: 'open',
    recruitmentDeadline: '2026-10-05T23:59:59Z',
    applicationsCount: 48,
  },
  {
    id: 'team_07',
    number: '07',
    name: 'Internship & Career Connect',
    slug: 'career-connect',
    accentColor: '#854D0E', // Bronze/Gold Dark
    themeBadge: 'bg-[#854D0E]/15 text-[#854D0E] border-[#854D0E]/30',
    tagline: 'Placing student builders into high-growth venture-backed startups.',
    mission: 'Connect talented campus developers, designers, and growth marketers directly with founders for paid early-stage internships.',
    overview: 'Team 07 operates the campus founder-talent pipeline, curating vetted opportunities at YC, Surge, and Antler portfolio startups.',
    headId: 'per-012',
    headName: 'Megha Singhal',
    headDesignation: 'Head, Career Connect',
    headPhoto: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
    coordinators: [],
    membersCount: 12,
    responsibilities: [
      { id: 'p-37', title: 'Startup Talent Drives', scope: 'Exclusive campus hiring sessions with series A/B venture-backed firms.' },
      { id: 'p-38', title: 'Resume & Portfolio Clinics', scope: '1-on-1 feedback on GitHub, Behance, and founder-focused CVs.' },
      { id: 'p-39', title: 'Shadow-a-Founder Program', scope: 'Pairing top 10 students each year to shadow venture founders for a week.' },
      { id: 'p-40', title: 'Early-Stage Stipend Grants', scope: 'Subsidizing student internships at early-stage pre-seed startups.' },
      { id: 'p-41', title: 'Startup Job Board', scope: 'Publishing weekly verified remote and on-site internship postings.' },
      { id: 'p-42', title: 'Alumni Recruiter Network', scope: 'Engaging alumni now working in tech leadership to source campus hires.' },
    ],
    socialLinks: { email: 'careers@gec.in' },
    gallery: [],
    recruitmentStatus: 'open',
    recruitmentDeadline: '2026-10-05T23:59:59Z',
    applicationsCount: 22,
  },
];

export const mockInitiatives: Initiative[] = [
  {
    id: 'init-001',
    title: 'Startup Development Program — Cohort 04',
    slug: 'sdp-cohort-04',
    cohortId: 'SDP-2026-C4',
    category: 'Program',
    status: 'Applications Open',
    featuredOnHome: true,
    excerpt: 'An intensive 10-week pre-incubation accelerator providing student founders with product architecture, legal incorporation, and seed grants.',
    description: 'The Startup Development Program is GEC’s flagship engine for campus ventures. Selected teams receive dedicated workspaces, AWS/GCP cloud credits, legal incorporation support, and pitch directly before institutional micro-funds.',
    coverImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80',
    stages: [
      {
        stageNum: '01',
        title: 'Application & Screening',
        targetDates: 'Sep 15 – Oct 10',
        description: 'Submission of pitch deck, problem validation data, and prototype demonstration.',
        status: 'current',
      },
      {
        stageNum: '02',
        title: 'Validation Bootcamp',
        targetDates: 'Oct 15 – Nov 05',
        description: '3 weeks of customer discovery interviews, unit economic modeling, and mentor pairing.',
        status: 'upcoming',
      },
      {
        stageNum: '03',
        title: 'MVP Build & Pilot',
        targetDates: 'Nov 10 – Dec 05',
        description: 'Deploying product with first 100 active campus/commercial users with technical support.',
        status: 'upcoming',
      },
      {
        stageNum: '04',
        title: 'Investor Demo Day',
        targetDates: 'Dec 15, 2026',
        description: 'Final closed-door pitch session before 20+ angel investors and seed fund partners.',
        status: 'upcoming',
      },
    ],
    eligibility: [
      'At least one co-founder must be a currently enrolled student at Galgotias University.',
      'Must have a clear problem statement and either an initial prototype, wireframe, or validation data.',
      'Commitment to attend all weekly mentor checkpoints throughout the 10-week cohort.',
    ],
    mentors: ['Dr. Vikramaditya Sen', 'Rohan Gupta', 'Alumni Mentors Network'],
    speakers: ['Siddharth Rao (Founder, ScaleHQ)', 'Neha Chawla (Partner, SeedVenture)'],
    faqs: [
      {
        question: 'Do we need to have a registered company before applying?',
        answer: 'No. The program assists promising student founders with legal incorporation, GST, and bank accounts during Stage 03.',
      },
      {
        question: 'Is equity taken by GEC?',
        answer: 'GEC operates as a university non-profit cell and does not take equity from student ventures during pre-incubation.',
      },
    ],
    ctaLabel: 'Submit Cohort Application',
    ctaUrl: '/forms/sdp-application',
    customFormFields: [
      { name: 'startup_name', label: 'Startup or Project Name', type: 'text', required: true },
      { name: 'pitch_deck', label: 'Pitch Deck PDF', type: 'file', required: true },
      { name: 'problem_statement', label: 'Problem & Value Proposition', type: 'textarea', required: true },
    ],
    submissionsCount: 64,
    updatedAt: '2026-09-20T08:00:00Z',
  },
  {
    id: 'init-002',
    title: 'Galgotias Ideathon 2026',
    slug: 'ideathon-2026',
    cohortId: 'ID-2026',
    category: 'Competition',
    status: 'Coming Soon',
    featuredOnHome: true,
    excerpt: '36-hour physical hackathon bringing together 800+ builders across AI, Climate, FinTech, and Hardware.',
    description: 'Northern India’s largest university hackathon, featuring ₹3,00,000 in cash prizes, direct entry to the GEC incubation funnel, and sponsored tracks from top developer ecosystems.',
    coverImage: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=1200&auto=format&fit=crop&q=80',
    stages: [
      { stageNum: '01', title: 'Problem Track Release', targetDates: 'Nov 01', description: 'Domain briefs unveiled.', status: 'upcoming' },
      { stageNum: '02', title: 'Registration & Team Lock', targetDates: 'Nov 15', description: 'Team formation up to 4 members.', status: 'upcoming' },
      { stageNum: '03', title: '36-Hour Hack Day', targetDates: 'Nov 28 – 30', description: 'Continuous physical sprint.', status: 'upcoming' },
      { stageNum: '04', title: 'Grand Finale & Demos', targetDates: 'Nov 30 Evening', description: 'Top 10 pitches on main stage.', status: 'upcoming' },
    ],
    eligibility: ['Open to undergraduate and postgraduate students nationwide with valid university ID.'],
    mentors: ['Technical Team Leads', 'Ecosystem Evangelists'],
    speakers: [],
    faqs: [
      { question: 'Is accommodation provided for outstation teams?', answer: 'Yes, overnight hostel accommodation and food are provided for shortlisted finalists.' },
    ],
    ctaLabel: 'Get Notified on Launch',
    ctaUrl: '/forms/ideathon-notify',
    customFormFields: [],
    submissionsCount: 142,
    updatedAt: '2026-09-18T14:30:00Z',
  },
  {
    id: 'init-003',
    title: 'Annual E-Summit 2026',
    slug: 'e-summit-2026',
    cohortId: 'SUMMIT-2026',
    category: 'Summit',
    status: 'Ongoing',
    featuredOnHome: true,
    excerpt: 'The premier national gathering of founders, angel investors, policy shapers, and collegiate entrepreneurs.',
    description: 'A 2-day flagship celebration with 15+ unicorn speakers, panel debates on sovereign AI, startup exhibitions, and student networking lounges.',
    coverImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&auto=format&fit=crop&q=80',
    stages: [],
    eligibility: ['Open to all students, faculty, and industry professionals.'],
    mentors: [],
    speakers: ['Industry Keynotes'],
    faqs: [],
    ctaLabel: 'Book Summit Pass',
    ctaUrl: '/initiatives/e-summit-2026',
    customFormFields: [],
    submissionsCount: 310,
    updatedAt: '2026-09-19T16:00:00Z',
  },
];

export const mockStories: Story[] = [
  {
    id: 'sty-001',
    title: 'From Dorm Hack to ₹50 Lakh Seed: How FleetOps Rebuilt Logistics from Campus',
    slug: 'dorm-hack-to-50-lakh-seed-fleetops',
    category: 'Founder Story',
    status: 'Published',
    author: 'Sneha Patel',
    authorRole: 'Editorial Head',
    readTime: '4 min read',
    coverImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=1000&auto=format&fit=crop&q=80',
    excerpt: 'GEC alumni founders Tanya Saxena and Rohan K. share their 18-month journey scaling an automated EV fleet dispatch system.',
    body: 'When Tanya Saxena joined the GEC Startup Development Program in 2024, she had little more than a Python script and an obsession with EV telematics. Fast forward eighteen months, FleetOps now powers over 400 delivery vehicles across Noida and Gurugram.\n\n"The earliest feedback from GEC Office Hours changed our trajectory," recalls Tanya. "Instead of building another generic dashboard, the mentors forced us into the field talking directly to fleet dispatchers."\n\nToday, FleetOps has closed its seed round led by an angel syndicate and is expanding into cold-chain logistics.',
    quote: 'GEC did not just give us a desk; they gave us the audacity to speak with investors as equals.',
    featuredOnHome: true, // Bento Slot 1
    featuredOnMagazineLead: true, // Page 05 §5.2
    publishedAt: '2026-09-18T10:00:00Z',
    viewsCount: 1420,
  },
  {
    id: 'sty-002',
    title: 'GEC Signs MoU with GICRISE to Expand Student Venture Seed Grants',
    slug: 'gec-gicrise-mou-announcement',
    category: 'News',
    status: 'Published',
    author: 'Aarav Sharma',
    authorRole: 'President, GEC',
    readTime: '3 min read',
    coverImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1000&auto=format&fit=crop&q=80',
    excerpt: 'A landmark institutional grant expands total available PoC funding for campus incubatees to ₹25 Lakhs per session.',
    body: 'The Galgotias Entrepreneurship Cell is proud to announce a renewed strategic charter with GICRISE. This institutional alliance introduces streamlined seed disbursement for high-readiness student ventures.',
    featuredOnHome: false,
    featuredOnMagazineLead: false,
    publishedAt: '2026-09-14T12:00:00Z',
    viewsCount: 890,
  },
  {
    id: 'sty-003',
    title: 'Building AI Agents in the Classroom: Devansh on Next-Gen Automation',
    slug: 'building-ai-agents-classroom',
    category: 'Startup Story',
    status: 'In Review',
    author: 'Rohan Gupta',
    authorRole: 'Tech Head',
    readTime: '5 min read',
    coverImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1000&auto=format&fit=crop&q=80',
    excerpt: 'A deep dive into how student engineers at GEC are combining Gemini models with local data stores for campus automation.',
    body: 'Autonomous agents are moving out of research labs and into operational student workflows. Here is what we learned compiling Google Forms via agent plans.',
    featuredOnHome: false,
    featuredOnMagazineLead: false,
    scheduledFor: '2026-09-25T10:00:00Z',
  },
];

export const mockPartners: Partner[] = [
  {
    id: 'part-01',
    name: 'GICRISE Incubation Foundation',
    category: 'Incubation',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    websiteUrl: 'https://galgotiasuniversity.edu.in',
    featuredOnHome: true,
    orderRank: 1,
  },
  {
    id: 'part-02',
    name: 'AWS for Startups',
    category: 'Cloud',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    websiteUrl: 'https://aws.amazon.com',
    featuredOnHome: true,
    orderRank: 2,
  },
  {
    id: 'part-03',
    name: 'NASSCOM 10,000 Startups',
    category: 'Corporate',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    websiteUrl: 'https://nasscom.in',
    featuredOnHome: true,
    orderRank: 3,
  },
];

export const mockSpeakers: Speaker[] = [
  {
    id: 'spk-01',
    name: 'Deepak Mehrotra',
    designation: 'Managing Director & Angel Investor',
    company: 'Nexus Capital',
    portraitUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
    eventName: 'Annual E-Summit 2026',
    socialUrl: 'https://linkedin.com',
    featuredOnHome: true,
  },
  {
    id: 'spk-02',
    name: 'Anjali Sharma',
    designation: 'Co-Founder & VP Product',
    company: 'FinFlow Technologies',
    portraitUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    eventName: 'FinTech Founder Roundtables',
    socialUrl: 'https://linkedin.com',
    featuredOnHome: true,
  },
];

export const mockStartups: Startup[] = [
  {
    id: 'stu-01',
    name: 'FleetOps EV',
    logoUrl: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200&auto=format&fit=crop&q=80',
    pitch: 'AI-driven commercial EV fleet telematics and predictive maintenance battery management.',
    founders: ['Tanya Saxena', 'Rohan K.'],
    cohortYear: '2025',
    sector: 'Climate',
    stage: 'Seed',
    websiteUrl: 'https://fleetops.in',
    featured: true,
  },
  {
    id: 'stu-02',
    name: 'DormKart',
    logoUrl: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200&auto=format&fit=crop&q=80',
    pitch: 'Hyperlocal 15-minute campus peer-to-peer textbook and gadget rental marketplace.',
    founders: ['Aman Jha', 'Karan Verma'],
    cohortYear: '2026',
    sector: 'Consumer',
    stage: 'Incubated',
    websiteUrl: 'https://dormkart.app',
    featured: true,
  },
  {
    id: 'stu-03',
    name: 'NeuralPulse Health',
    logoUrl: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200&auto=format&fit=crop&q=80',
    pitch: 'Low-cost embedded hardware sensor for early diabetic neuropathy screening.',
    founders: ['Priya Nair'],
    cohortYear: '2026',
    sector: 'Health',
    stage: 'Idea Lab',
    websiteUrl: 'https://neuralpulse.tech',
    featured: false,
  },
];

export const mockAlumni: Alumni[] = [
  {
    id: 'alm-01',
    name: 'Saurabh Chandra',
    currentRole: 'CTO & Co-Founder',
    company: 'PayZest (YC W24)',
    graduationYear: '2023',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    linkedinUrl: 'https://linkedin.com',
    testimonial: 'GEC was where I built my first web app and found my co-founder. The culture of peer accountability is unmatched.',
  },
  {
    id: 'alm-02',
    name: 'Divya Rastogi',
    currentRole: 'Principal Product Designer',
    company: 'Razorpay',
    graduationYear: '2024',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
    linkedinUrl: 'https://linkedin.com',
    testimonial: 'Leading design for GEC taught me how to communicate brand energy without sacrificing UX clarity.',
  },
];

export const mockMediaAssets: MediaAsset[] = [
  {
    id: 'med-001',
    name: 'sdp-cohort-4-loop-16x9.mp4',
    category: 'Videos',
    aspectRatio: '16:9',
    cdnUrl: 'https://media-staging.gec.in/videos/sdp-cohort-4-loop-16x9.mp4',
    key: 'public/hero/hero-camp-001/med-001/v1-sdp-cohort-4-loop.mp4',
    mimeType: 'video/mp4',
    sizeBytes: 8450120,
    referenceCount: 1,
    references: ['Homepage Dynamic Hero Spotlight §1.1'],
    uploadedAt: '2026-09-15T08:30:00Z',
    uploadedBy: 'Aarav Sharma',
  },
  {
    id: 'med-002',
    name: 'sdp-cohort-4-mobile-9x16.mp4',
    category: 'Videos',
    aspectRatio: '9:16',
    cdnUrl: 'https://media-staging.gec.in/videos/sdp-cohort-4-loop-9x16.mp4',
    key: 'public/hero/hero-camp-001/med-002/v1-sdp-cohort-4-mobile.mp4',
    mimeType: 'video/mp4',
    sizeBytes: 5120400,
    referenceCount: 1,
    references: ['Homepage Dynamic Hero Mobile Poster §1.1'],
    uploadedAt: '2026-09-15T08:32:00Z',
    uploadedBy: 'Aarav Sharma',
  },
  {
    id: 'med-003',
    name: 'gec-primary-crest-vector.svg',
    category: 'Brand Assets',
    aspectRatio: '1:1',
    cdnUrl: 'https://media-staging.gec.in/brand/gec-crest.svg',
    key: 'public/brand/med-003/v1-gec-crest.svg',
    mimeType: 'image/svg+xml',
    sizeBytes: 42300,
    referenceCount: 4,
    references: ['Header Navigation', 'Footer Brand Block', 'CMS Shell', 'Email Templates'],
    uploadedAt: '2026-09-01T10:00:00Z',
    uploadedBy: 'Rohan Gupta',
  },
  {
    id: 'med-004',
    name: 'tanya-saxena-founder-portrait.jpg',
    category: 'Images',
    aspectRatio: '3:4',
    cdnUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80',
    key: 'public/stories/sty-001/med-004/v1-tanya-saxena.jpg',
    mimeType: 'image/jpeg',
    sizeBytes: 1240500,
    referenceCount: 2,
    references: ['Story §5.2 Lead Feature', 'Bento Card 01'],
    uploadedAt: '2026-09-18T09:00:00Z',
    uploadedBy: 'Sneha Patel',
  },
  {
    id: 'med-005',
    name: 'ideathon-hero-poster-16x9.jpg',
    category: 'Images',
    aspectRatio: '16:9',
    cdnUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=1200&auto=format&fit=crop&q=80',
    key: 'public/initiatives/init-002/med-005/v1-ideathon.jpg',
    mimeType: 'image/jpeg',
    sizeBytes: 2420000,
    referenceCount: 1,
    references: ['Initiatives Detail Canvas §4.2'],
    uploadedAt: '2026-09-18T14:00:00Z',
    uploadedBy: 'Rohan Gupta',
  },
];

export const mockSubmissions: Submission[] = [
  {
    id: 'sub-101',
    formType: 'Initiative Application',
    applicantName: 'Vikram Rajput',
    applicantEmail: 'vikram.rajput26@galgotias.edu',
    applicantPhone: '+91 98765 43210',
    initiativeTarget: 'Startup Development Program — Cohort 04',
    status: 'New',
    submittedAt: '2026-09-20T10:14:22Z',
    attachmentUrl: 'https://r2.gec.in/private/submissions/sub-101/deck.pdf',
    answers: {
      'Project Title': 'Kavach IoT — Smart Campus Energy Monitor',
      'Team Size': '3 Members',
      'Stage': 'Working Breadboard Prototype',
      'Problem Description': 'Hostels waste 34% electricity due to unmanaged AC units during class hours. Kavach installs non-invasive split-core current transformers.',
    },
    notes: 'Strong technical thesis. Needs business model validation.',
  },
  {
    id: 'sub-102',
    formType: 'Join Team Application',
    applicantName: 'Nisha Sundaram',
    applicantEmail: 'nisha.sundaram@galgotias.edu',
    applicantPhone: '+91 91234 56789',
    teamTarget: 'Team 06: Technical Team',
    status: 'Shortlisted',
    submittedAt: '2026-09-19T17:45:10Z',
    attachmentUrl: 'https://r2.gec.in/private/submissions/sub-102/resume.pdf',
    answers: {
      'Target Role': 'Fullstack Developer',
      'GitHub Profile': 'https://github.com/nishasundaram',
      'Key Projects': 'Built a real-time collaborative whiteboard using WebSockets and Next.js.',
      'Why GEC?': 'Want to work on mission-critical digital systems powering real student initiatives.',
    },
    notes: 'Outstanding GitHub portfolio. Scheduled for technical interview on Wednesday.',
  },
  {
    id: 'sub-103',
    formType: 'Startup Pitch',
    applicantName: 'Aditya Mathur',
    applicantEmail: 'aditya@synapseflow.ai',
    applicantPhone: '+91 99887 76655',
    status: 'Reviewed',
    submittedAt: '2026-09-18T11:20:00Z',
    answers: {
      'Startup Name': 'SynapseFlow AI',
      'One Line Pitch': 'Voice AI receptionist for regional pathology diagnostic labs.',
      'Current Traction': '₹45,000 MRR across 6 clinic pilots in Noida.',
    },
  },
];

export const mockGoogleForms: GoogleForm[] = [
  {
    id: 'gf-001',
    title: 'GEC Cohort 04 — Founder Intake & Pitch Evaluation',
    description: 'Official application portal for early-stage collegiate founders seeking pre-incubation grants and mentor matching.',
    lifecycleState: 'needs_manual_upload_setup',
    responderUri: 'https://docs.google.com/forms/d/e/1FAIpQLScD_sample01/viewform',
    editUri: 'https://docs.google.com/forms/d/1FAIpQLScD_sample01/edit',
    manualUploadSetupRequired: true,
    manualUploadVerified: false,
    manualItemIds: [],
    lastResponseSyncAt: '2026-09-20T09:15:00Z',
    responseCount: 64,
    driveFolderId: 'folder_automation_001',
    sheetUrl: 'https://docs.google.com/spreadsheets/d/1sampleSheet01/edit',
    items: [
      { id: 'i-1', title: 'Founder Full Name', kind: 'text', required: true },
      { id: 'i-2', title: 'University Enrollment Number', kind: 'text', required: true },
      { id: 'i-3', title: 'Startup Sector', kind: 'choice', required: true, options: ['Tech & AI', 'Consumer / D2C', 'Health & Bio', 'Climate & Cleantech', 'Fintech', 'Other'] },
      { id: 'i-4', title: 'Upload Pitch Deck (PDF only, max 25MB)', kind: 'file_upload', required: true, isManualFileUpload: true },
      { id: 'i-5', title: 'Estimated Seed Grant Capital Required (INR)', kind: 'choice', required: true, options: ['Up to ₹50,000', '₹1,00,000 – ₹2,50,000', '₹5,00,000'] },
    ],
    createdAt: '2026-09-15T10:00:00Z',
    updatedAt: '2026-09-20T09:15:00Z',
  },
  {
    id: 'gf-002',
    title: 'Galgotias Ideathon 2026 — Team Pre-Registration',
    description: 'Express interest and receive early problem track briefs before the national portal opens.',
    lifecycleState: 'published',
    responderUri: 'https://docs.google.com/forms/d/e/1FAIpQLScD_sample02/viewform',
    editUri: 'https://docs.google.com/forms/d/1FAIpQLScD_sample02/edit',
    manualUploadSetupRequired: false,
    manualUploadVerified: true,
    manualItemIds: [],
    lastResponseSyncAt: '2026-09-20T11:30:00Z',
    responseCount: 142,
    sheetUrl: 'https://docs.google.com/spreadsheets/d/1sampleSheet02/edit',
    items: [
      { id: 'i-6', title: 'Team Leader Name', kind: 'text', required: true },
      { id: 'i-7', title: 'Team Leader Email', kind: 'text', required: true },
      { id: 'i-8', title: 'College / Institute Name', kind: 'text', required: true },
      { id: 'i-9', title: 'Preferred Problem Domain', kind: 'choice', required: true, options: ['Smart Cities', 'Autonomous Robotics', 'Cybersecurity', 'Decentralized Finance'] },
    ],
    createdAt: '2026-09-10T08:00:00Z',
    updatedAt: '2026-09-20T11:30:00Z',
  },
];

export const mockGoogleFormResponses: GoogleFormResponse[] = [
  {
    id: 'gfr-001',
    formId: 'gf-001',
    responseId: 'resp_aaa_101',
    submittedAt: '2026-09-20T08:42:10Z',
    respondentEmail: 'arjun.mehta@galgotias.edu',
    answers: {
      'Founder Full Name': 'Arjun Mehta',
      'University Enrollment Number': 'GU23BTECHCS104',
      'Startup Sector': 'Tech & AI',
      'Upload Pitch Deck (PDF only, max 25MB)': 'https://drive.google.com/file/d/sample_deck_01',
      'Estimated Seed Grant Capital Required (INR)': '₹1,00,000 – ₹2,50,000',
    },
  },
  {
    id: 'gfr-002',
    formId: 'gf-001',
    responseId: 'resp_aaa_102',
    submittedAt: '2026-09-20T07:15:30Z',
    respondentEmail: 'priya.sharma@galgotias.edu',
    answers: {
      'Founder Full Name': 'Priya Sharma',
      'University Enrollment Number': 'GU24BBAENT018',
      'Startup Sector': 'Consumer / D2C',
      'Upload Pitch Deck (PDF only, max 25MB)': 'https://drive.google.com/file/d/sample_deck_02',
      'Estimated Seed Grant Capital Required (INR)': 'Up to ₹50,000',
    },
  },
];

export const mockCopilotMessages: CopilotMessage[] = [
  {
    id: 'msg-01',
    conversationId: 'conv-001',
    role: 'user',
    content: 'Can you help update the headline for the Hero Spotlight to emphasize the 48-hour deadline for Cohort 04?',
    timestamp: '2026-09-20T11:40:00Z',
  },
  {
    id: 'msg-02',
    conversationId: 'conv-001',
    role: 'assistant',
    content: 'I have prepared a draft update for the Hero Spotlight. It changes the lifecycle state to "Urgency / Deadline" and updates the eyebrow badge to "[48 HOURS LEFT]". As per GEC governance rules, publishing or updating a hero spotlight requires your 1-click confirmation.',
    timestamp: '2026-09-20T11:40:05Z',
    proposal: {
      id: 'prop-001',
      conversationId: 'conv-001',
      actionType: 'update_draft',
      targetId: 'hero-camp-001',
      targetVersion: 'v1.2',
      preview: {
        summary: 'Update Hero Spotlight status to Urgency and add 48-hour deadline badge',
        details: {
          target: 'Hero Spotlight Campaign #001',
          urgencyLevel: 'High',
        },
        diff: [
          { field: 'Status', before: 'Applications Open', after: 'Urgency / Deadline' },
          { field: 'Eyebrow / Badge', before: 'APPLICATIONS OPEN · COHORT 04', after: '48 HOURS LEFT · FINAL APPLICATION WINDOW' },
          { field: 'Supporting Text', before: 'Have a validated problem or prototype? Join northern India’s premier university incubation funnel with seed grants up to ₹5 Lakhs.', after: 'Final 48 hours to apply for Cohort 04. Applications close promptly at midnight.' },
        ],
      },
      status: 'proposed',
      expiresAt: '2026-09-20T12:40:05Z',
      idempotencyKey: 'idem-hero-urgency-001',
    },
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'aud-001',
    actorName: 'Aarav Sharma',
    actorEmail: 'president@gec.in',
    action: 'CONTENT_PUBLISH',
    resource: 'Hero Spotlight Campaign',
    resourceId: 'hero-camp-001',
    details: 'Published SDP Cohort 04 campaign to live website hero §1.1',
    timestamp: '2026-09-20T08:00:00Z',
    ipAddress: '103.21.14.88',
  },
  {
    id: 'aud-002',
    actorName: 'Sneha Patel',
    actorEmail: 'editorial@gec.in',
    action: 'STORY_UPDATE',
    resource: 'Story: sty-001',
    resourceId: 'sty-001',
    details: 'Pinned FleetOps founder story to Magazine Spread Lead (Page 05 §5.2)',
    timestamp: '2026-09-19T16:20:00Z',
    ipAddress: '103.21.14.92',
  },
  {
    id: 'aud-003',
    actorName: 'Rohan Gupta',
    actorEmail: 'tech.head@gec.in',
    action: 'CACHE_PURGE',
    resource: 'Cloudflare CDN',
    details: 'Triggered global cache invalidation across all 5 public website routes',
    timestamp: '2026-09-19T14:15:00Z',
    ipAddress: '103.21.14.95',
  },
  {
    id: 'aud-004',
    actorName: 'Pooja Verma',
    actorEmail: 'admin.core@gec.in',
    action: 'FORM_CREATE',
    resource: 'Google Form gf-001',
    resourceId: 'gf-001',
    details: 'Created managed Google Form plan with manual upload checkpoint requirement',
    timestamp: '2026-09-15T10:02:00Z',
    ipAddress: '103.21.14.84',
  },
];

export const mockSiteSettings: SiteSettings = {
  general: {
    siteName: 'Galgotias Entrepreneurship Cell',
    portalName: 'GEC Digital Command Center',
    environment: 'staging',
    liveSyncStatus: 'synced',
    lastSyncTimestamp: '2026-09-20T12:00:00Z',
  },
  announcementTicker: {
    enabled: true,
    text: 'Applications for Startup Development Program Cohort 04 close in 48 hours. Submit pitch deck now →',
    linkUrl: '/initiatives/sdp-cohort-04',
    highlightWord: 'Cohort 04',
  },
  impactCounters: {
    startupsIncubated: 140,
    eventsConducted: 85,
    studentFootfall: 42000,
    fundingRaisedLakhs: 380, // ₹3.8 Crores
  },
  seoDefaults: {
    metaTitle: 'Galgotias Entrepreneurship Cell | Ideas Begin Here',
    metaDescription: 'Official entrepreneurship and incubation community of Galgotias University. Empowering student founders with seed capital, mentors, and incubation.',
    ogImageUrl: 'https://media-staging.gec.in/brand/og-share-card.png',
    keywords: 'GEC, Galgotias University, E-Cell, Startup Incubation, Student Founders, Entrepreneurship, NCR Tech',
  },
  socialLinks: {
    instagram: 'https://instagram.com/gec_galgotias',
    linkedin: 'https://linkedin.com/company/galgotias-entrepreneurship-cell',
    twitter: 'https://x.com/gec_galgotias',
    youtube: 'https://youtube.com/@gec_galgotias',
    discord: 'https://discord.gg/gec',
  },
  contactInfo: {
    email: 'contact@gec.in',
    supportEmail: 'support@gec.in',
    phone: '+91 (0120) 4370000',
    location: 'Block A, Innovation Hub & Incubation Lab, Galgotias University, Greater Noida, UP 203201',
  },
};
