"use client";

import { FormEvent, useState } from "react";
import type { PublicTeam } from "@/lib/content-types";

export function TeamRecruitmentForm({ team }: { team: PublicTeam }) {
  const [state, setState] = useState<"idle" | "pending" | "success" | "error">("idle");
  const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const applicantName = String(form.get("name") || "").trim(); const applicantEmail = String(form.get("email") || "").trim();
    if (!applicantName || !/^\S+@\S+\.\S+$/.test(applicantEmail)) { setState("error"); setMessage("Enter your name and a valid email address."); return; }
    setState("pending"); setMessage("");
    try { const response = await fetch("/api/submissions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ submissionType: "recruitment", targetEntityId: team.id, applicantName, applicantEmail, applicantPhone: String(form.get("phone") || "").trim() || undefined, payload: { teamSlug: team.slug, interest: String(form.get("interest") || "").trim() } }) }); const result = await response.json().catch(() => null); if (!response.ok || !result?.success) throw new Error(typeof result?.error === "string" ? result.error : "We couldn’t send that right now. Please try again."); event.currentTarget.reset(); setState("success"); setMessage("Thanks — your interest has been received."); } catch (error) { setState("error"); setMessage(error instanceof Error ? error.message : "We couldn’t send that right now. Please try again."); }
  }
  return <form className="mt-8 min-w-0 max-w-full border-t border-[var(--gec-border)] pt-6" onSubmit={submit} noValidate><h3 className="text-lg font-extrabold text-[var(--gec-ink)]">Join this team</h3><p className="mt-1 text-sm text-[var(--gec-ink-muted)]">Tell us how you&apos;d like to contribute.</p><div className="mt-4 grid min-w-0 gap-3 sm:grid-cols-2"><label className="text-sm font-semibold text-[var(--gec-ink)]">Name<input name="name" required className="mt-1 min-h-11 min-w-0 w-full rounded-lg border border-[var(--gec-border)] bg-white px-3" /></label><label className="text-sm font-semibold text-[var(--gec-ink)]">Email<input name="email" required type="email" className="mt-1 min-h-11 min-w-0 w-full rounded-lg border border-[var(--gec-border)] bg-white px-3" /></label><label className="text-sm font-semibold text-[var(--gec-ink)]">Phone <span className="font-normal">(optional)</span><input name="phone" type="tel" className="mt-1 min-h-11 min-w-0 w-full rounded-lg border border-[var(--gec-border)] bg-white px-3" /></label><label className="text-sm font-semibold text-[var(--gec-ink)]">What interests you?<input name="interest" className="mt-1 min-h-11 min-w-0 w-full rounded-lg border border-[var(--gec-border)] bg-white px-3" /></label></div><button disabled={state === "pending"} className="mt-4 inline-flex min-h-12 items-center justify-center rounded-lg bg-[var(--gec-crimson)] px-5 font-bold text-white disabled:opacity-60" type="submit">{state === "pending" ? "Sending…" : "Share your interest"}</button>{message ? <p className={`mt-3 text-sm font-semibold ${state === "error" ? "text-[var(--gec-crimson)]" : "text-[var(--gec-ink)]"}`} aria-live="polite">{message}</p> : null}</form>;
}
