import Link from "next/link";
import type { PublicPerson } from "@/lib/content-types";

type AboutContentProps = { people: PublicPerson[] };

const milestones = [
  ["A community begins", "GEC brings together students who want to explore entrepreneurship beyond the classroom."],
  ["Learning through participation", "Workshops, conversations, pitching, and collaborative projects make room for students to learn by doing."],
  ["Part of a wider ecosystem", "GEC works alongside GICRISE, the Galgotias Incubation Centre for Research, Innovation, Startup & Entrepreneurs."],
] as const;

function PersonCard({ person }: { person: PublicPerson }) {
  return <article className="rounded-xl border border-[var(--gec-border)] bg-[var(--gec-surface-card)] p-5 shadow-[var(--shadow-ambient)]"><p className="text-sm font-bold text-[var(--gec-crimson)]">{person.roleTitle}</p><h3 className="mt-2 text-xl font-extrabold tracking-[-0.02em] text-[var(--gec-ink)]">{person.name}</h3>{person.data.bio ? <p className="mt-3 text-sm leading-6 text-[var(--gec-ink-muted)]">{person.data.bio}</p> : null}{person.data.socialLinks?.linkedin ? <a className="mt-4 inline-flex min-h-11 items-center font-semibold text-[var(--gec-crimson)] underline underline-offset-4" href={person.data.socialLinks.linkedin}>LinkedIn</a> : null}</article>;
}

export function AboutContent({ people }: AboutContentProps) {
  const leadership = people.filter((person) => person.category === "leadership");
  const mentors = people.filter((person) => person.category === "mentors");
  return <div className="min-w-0 max-w-full overflow-x-hidden">
    <section className="mx-auto max-w-4xl px-5 py-20 text-center sm:px-8 lg:py-28"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[var(--gec-crimson)]">About GEC</p><h1 className="mt-5 text-balance font-[family-name:var(--font-display)] text-[clamp(2.5rem,5vw,4.5rem)] font-black leading-[1.05] tracking-[-0.04em] text-[var(--gec-ink)]">We don&apos;t just talk about entrepreneurship. We create space to experience it.</h1><p className="mx-auto mt-7 max-w-3xl text-pretty text-lg leading-8 text-[var(--gec-ink-muted)]">Galgotias Entrepreneurship Cell is a student-driven community built around innovation, leadership, creativity, and entrepreneurship.</p></section>
    <section className="border-y border-[var(--gec-border)] bg-[var(--gec-surface-sand)] px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-[var(--gec-crimson)]">Our story</p><h2 className="mt-4 text-balance text-[clamp(1.9rem,3.5vw,2.75rem)] font-extrabold leading-tight tracking-[-0.03em] text-[var(--gec-ink)]">From curiosity to community.</h2><div className="mt-6 space-y-4 text-pretty leading-7 text-[var(--gec-ink-muted)]"><p>GEC exists to bring together students who want to think differently, solve problems, and explore entrepreneurship beyond classrooms.</p><p>The community grows around startup development, pitching sessions, workshops, founder interactions, networking, and practical experiences that allow students to participate in entrepreneurship.</p></div></div><aside className="rounded-2xl border border-[var(--gec-border)] bg-[var(--gec-surface-card)] p-7 shadow-[var(--shadow-ambient)] sm:p-9"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[var(--gec-blue)]">GEC × GICRISE</p><h3 className="mt-4 text-2xl font-extrabold tracking-[-0.025em] text-[var(--gec-ink)]">An ecosystem with room to grow.</h3><p className="mt-4 leading-7 text-[var(--gec-ink-muted)]">GEC works within the wider Galgotias innovation ecosystem alongside GICRISE. GICRISE supports startups and student innovators through mentorship, exposure, networking, incubation, and growth opportunities.</p></aside></div></section>
    <section className="mx-auto grid max-w-6xl gap-6 px-5 py-16 sm:px-8 lg:grid-cols-2 lg:py-24">{[['Mission', 'Create builders, not spectators.', 'We foster an entrepreneurial mindset by creating opportunities to ideate, collaborate, experiment, lead, and execute.'], ['Vision', 'A campus where ideas have somewhere to go.', 'We aim to build a student entrepreneurship ecosystem where ambitious ideas can find collaborators, guidance, opportunities, and a pathway toward impactful ventures.']].map(([label, title, copy]) => <article key={label} className="rounded-2xl border border-[var(--gec-border)] bg-[var(--gec-surface-card)] p-7 shadow-[var(--shadow-ambient)] sm:p-9"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[var(--gec-crimson)]">{label}</p><h2 className="mt-5 text-balance text-3xl font-extrabold leading-tight tracking-[-0.03em] text-[var(--gec-ink)]">{title}</h2><p className="mt-5 max-w-prose leading-7 text-[var(--gec-ink-muted)]">{copy}</p></article>)}</section>
    <section className="bg-[var(--gec-surface-sand)] px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[var(--gec-crimson)]">Student-led. Mentor-guided.</p><h2 className="mt-4 text-balance text-[clamp(1.9rem,3.5vw,2.75rem)] font-extrabold tracking-[-0.03em] text-[var(--gec-ink)]">People helping the community move.</h2>{leadership.length || mentors.length ? <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{[...leadership, ...mentors].map((person) => <PersonCard key={person.id} person={person} />)}</div> : <p className="mt-6 max-w-2xl leading-7 text-[var(--gec-ink-muted)]">Leadership and mentor profiles will appear here as current roles are confirmed.</p>}<div className="mt-12 flex flex-col justify-between gap-5 rounded-2xl border border-[var(--gec-border)] bg-[var(--gec-surface-card)] p-7 sm:flex-row sm:items-center"><div><h3 className="text-2xl font-extrabold tracking-[-0.025em] text-[var(--gec-ink)]">Seven teams. One vision.</h3><p className="mt-2 text-[var(--gec-ink-muted)]">Meet the student teams that turn ideas into action.</p></div><Link className="inline-flex min-h-12 items-center justify-center rounded-lg bg-[var(--gec-crimson)] px-6 font-bold text-white transition-transform hover:-translate-y-0.5 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--gec-crimson)] active:translate-y-px" href="/teams">Meet our teams</Link></div></div></section>
    <section className="mx-auto max-w-5xl px-5 py-16 sm:px-8 lg:py-24"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[var(--gec-crimson)]">Built through moments</p><h2 className="mt-4 text-balance text-[clamp(1.9rem,3.5vw,2.75rem)] font-extrabold tracking-[-0.03em] text-[var(--gec-ink)]">A community shaped by participation.</h2><ol className="mt-10 space-y-6 border-l-2 border-[var(--gec-crimson)] pl-7">{milestones.map(([title, copy]) => <li key={title}><h3 className="text-xl font-bold text-[var(--gec-ink)]">{title}</h3><p className="mt-2 max-w-2xl leading-7 text-[var(--gec-ink-muted)]">{copy}</p></li>)}</ol></section>
  </div>;
}
